//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_Planos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.imedexsa.es/", ConfigurationName="WebService_Planos.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento marca del espacio de nombres http://www.imedexsa.es/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imedexsa.es/ObtenerFile", ReplyAction="*")]
        WebService_Planos.ObtenerFileResponse ObtenerFile(WebService_Planos.ObtenerFileRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento marca del espacio de nombres http://www.imedexsa.es/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imedexsa.es/ObtenerFile2", ReplyAction="*")]
        WebService_Planos.ObtenerFile2Response ObtenerFile2(WebService_Planos.ObtenerFile2Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://www.imedexsa.es/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.imedexsa.es/EliminarTemporales", ReplyAction="*")]
        WebService_Planos.EliminarTemporalesResponse EliminarTemporales(WebService_Planos.EliminarTemporalesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFile", Namespace="http://www.imedexsa.es/", Order=0)]
        public WebService_Planos.ObtenerFileRequestBody Body;
        
        public ObtenerFileRequest() {
        }
        
        public ObtenerFileRequest(WebService_Planos.ObtenerFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imedexsa.es/")]
    public partial class ObtenerFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codemp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        public ObtenerFileRequestBody() {
        }
        
        public ObtenerFileRequestBody(string marca, string codemp, string user) {
            this.marca = marca;
            this.codemp = codemp;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFileResponse", Namespace="http://www.imedexsa.es/", Order=0)]
        public WebService_Planos.ObtenerFileResponseBody Body;
        
        public ObtenerFileResponse() {
        }
        
        public ObtenerFileResponse(WebService_Planos.ObtenerFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imedexsa.es/")]
    public partial class ObtenerFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerFileResult;
        
        public ObtenerFileResponseBody() {
        }
        
        public ObtenerFileResponseBody(string ObtenerFileResult) {
            this.ObtenerFileResult = ObtenerFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFile2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFile2", Namespace="http://www.imedexsa.es/", Order=0)]
        public WebService_Planos.ObtenerFile2RequestBody Body;
        
        public ObtenerFile2Request() {
        }
        
        public ObtenerFile2Request(WebService_Planos.ObtenerFile2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imedexsa.es/")]
    public partial class ObtenerFile2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codemp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        public ObtenerFile2RequestBody() {
        }
        
        public ObtenerFile2RequestBody(string marca, string codemp, string user) {
            this.marca = marca;
            this.codemp = codemp;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerFile2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerFile2Response", Namespace="http://www.imedexsa.es/", Order=0)]
        public WebService_Planos.ObtenerFile2ResponseBody Body;
        
        public ObtenerFile2Response() {
        }
        
        public ObtenerFile2Response(WebService_Planos.ObtenerFile2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imedexsa.es/")]
    public partial class ObtenerFile2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerFile2Result;
        
        public ObtenerFile2ResponseBody() {
        }
        
        public ObtenerFile2ResponseBody(string ObtenerFile2Result) {
            this.ObtenerFile2Result = ObtenerFile2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarTemporalesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarTemporales", Namespace="http://www.imedexsa.es/", Order=0)]
        public WebService_Planos.EliminarTemporalesRequestBody Body;
        
        public EliminarTemporalesRequest() {
        }
        
        public EliminarTemporalesRequest(WebService_Planos.EliminarTemporalesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imedexsa.es/")]
    public partial class EliminarTemporalesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        public EliminarTemporalesRequestBody() {
        }
        
        public EliminarTemporalesRequestBody(string user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarTemporalesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarTemporalesResponse", Namespace="http://www.imedexsa.es/", Order=0)]
        public WebService_Planos.EliminarTemporalesResponseBody Body;
        
        public EliminarTemporalesResponse() {
        }
        
        public EliminarTemporalesResponse(WebService_Planos.EliminarTemporalesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.imedexsa.es/")]
    public partial class EliminarTemporalesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EliminarTemporalesResult;
        
        public EliminarTemporalesResponseBody() {
        }
        
        public EliminarTemporalesResponseBody(string EliminarTemporalesResult) {
            this.EliminarTemporalesResult = EliminarTemporalesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WebService_Planos.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WebService_Planos.ServiceSoap>, WebService_Planos.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_Planos.ObtenerFileResponse WebService_Planos.ServiceSoap.ObtenerFile(WebService_Planos.ObtenerFileRequest request) {
            return base.Channel.ObtenerFile(request);
        }
        
        public string ObtenerFile(string marca, string codemp, string user) {
            WebService_Planos.ObtenerFileRequest inValue = new WebService_Planos.ObtenerFileRequest();
            inValue.Body = new WebService_Planos.ObtenerFileRequestBody();
            inValue.Body.marca = marca;
            inValue.Body.codemp = codemp;
            inValue.Body.user = user;
            WebService_Planos.ObtenerFileResponse retVal = ((WebService_Planos.ServiceSoap)(this)).ObtenerFile(inValue);
            return retVal.Body.ObtenerFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_Planos.ObtenerFile2Response WebService_Planos.ServiceSoap.ObtenerFile2(WebService_Planos.ObtenerFile2Request request) {
            return base.Channel.ObtenerFile2(request);
        }
        
        public string ObtenerFile2(string marca, string codemp, string user) {
            WebService_Planos.ObtenerFile2Request inValue = new WebService_Planos.ObtenerFile2Request();
            inValue.Body = new WebService_Planos.ObtenerFile2RequestBody();
            inValue.Body.marca = marca;
            inValue.Body.codemp = codemp;
            inValue.Body.user = user;
            WebService_Planos.ObtenerFile2Response retVal = ((WebService_Planos.ServiceSoap)(this)).ObtenerFile2(inValue);
            return retVal.Body.ObtenerFile2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService_Planos.EliminarTemporalesResponse WebService_Planos.ServiceSoap.EliminarTemporales(WebService_Planos.EliminarTemporalesRequest request) {
            return base.Channel.EliminarTemporales(request);
        }
        
        public string EliminarTemporales(string user) {
            WebService_Planos.EliminarTemporalesRequest inValue = new WebService_Planos.EliminarTemporalesRequest();
            inValue.Body = new WebService_Planos.EliminarTemporalesRequestBody();
            inValue.Body.user = user;
            WebService_Planos.EliminarTemporalesResponse retVal = ((WebService_Planos.ServiceSoap)(this)).EliminarTemporales(inValue);
            return retVal.Body.EliminarTemporalesResult;
        }
    }
}
