//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

using System.Collections.Generic;
namespace ProyectosOnLine {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("BonoEtiquetas")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class BonoEtiquetas : global::System.Data.DataSet {
        
        private TC_V_BONO_ETIQUETADataTable tableTC_V_BONO_ETIQUETA;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public BonoEtiquetas() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected BonoEtiquetas(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["TC_V_BONO_ETIQUETA"] != null)) {
                    base.Tables.Add(new TC_V_BONO_ETIQUETADataTable(ds.Tables["TC_V_BONO_ETIQUETA"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public TC_V_BONO_ETIQUETADataTable TC_V_BONO_ETIQUETA {
            get {
                return this.tableTC_V_BONO_ETIQUETA;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataSet Clone() {
            BonoEtiquetas cln = ((BonoEtiquetas)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["TC_V_BONO_ETIQUETA"] != null)) {
                    base.Tables.Add(new TC_V_BONO_ETIQUETADataTable(ds.Tables["TC_V_BONO_ETIQUETA"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars(bool initTable) {
            this.tableTC_V_BONO_ETIQUETA = ((TC_V_BONO_ETIQUETADataTable)(base.Tables["TC_V_BONO_ETIQUETA"]));
            if ((initTable == true)) {
                if ((this.tableTC_V_BONO_ETIQUETA != null)) {
                    this.tableTC_V_BONO_ETIQUETA.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.DataSetName = "BonoEtiquetas";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/BonoEtiquetas.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableTC_V_BONO_ETIQUETA = new TC_V_BONO_ETIQUETADataTable();
            base.Tables.Add(this.tableTC_V_BONO_ETIQUETA);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private bool ShouldSerializeTC_V_BONO_ETIQUETA() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            BonoEtiquetas ds = new BonoEtiquetas();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public delegate void TC_V_BONO_ETIQUETARowChangeEventHandler(object sender, TC_V_BONO_ETIQUETARowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class TC_V_BONO_ETIQUETADataTable : global::System.Data.TypedTableBase<TC_V_BONO_ETIQUETARow> {
            
            private global::System.Data.DataColumn columnBONO;
            
            private global::System.Data.DataColumn columnEtiqueta;
            
            private global::System.Data.DataColumn columnctd_a_fichar;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TC_V_BONO_ETIQUETADataTable() {
                this.TableName = "TC_V_BONO_ETIQUETA";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal TC_V_BONO_ETIQUETADataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected TC_V_BONO_ETIQUETADataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn BONOColumn {
                get {
                    return this.columnBONO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn EtiquetaColumn {
                get {
                    return this.columnEtiqueta;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataColumn ctd_a_ficharColumn {
                get {
                    return this.columnctd_a_fichar;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TC_V_BONO_ETIQUETARow this[int index] {
                get {
                    return ((TC_V_BONO_ETIQUETARow)(this.Rows[index]));
                }
            }
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TC_V_BONO_ETIQUETARowChangeEventHandler TC_V_BONO_ETIQUETARowChanging;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TC_V_BONO_ETIQUETARowChangeEventHandler TC_V_BONO_ETIQUETARowChanged;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TC_V_BONO_ETIQUETARowChangeEventHandler TC_V_BONO_ETIQUETARowDeleting;
            
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public event TC_V_BONO_ETIQUETARowChangeEventHandler TC_V_BONO_ETIQUETARowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void AddTC_V_BONO_ETIQUETARow(TC_V_BONO_ETIQUETARow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TC_V_BONO_ETIQUETARow AddTC_V_BONO_ETIQUETARow(int BONO, double ctd_a_fichar) {
                TC_V_BONO_ETIQUETARow rowTC_V_BONO_ETIQUETARow = ((TC_V_BONO_ETIQUETARow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        BONO,
                        null,
                        ctd_a_fichar};
                rowTC_V_BONO_ETIQUETARow.ItemArray = columnValuesArray;
                this.Rows.Add(rowTC_V_BONO_ETIQUETARow);
                return rowTC_V_BONO_ETIQUETARow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public override global::System.Data.DataTable Clone() {
                TC_V_BONO_ETIQUETADataTable cln = ((TC_V_BONO_ETIQUETADataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataTable CreateInstance() {
                return new TC_V_BONO_ETIQUETADataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal void InitVars() {
                this.columnBONO = base.Columns["BONO"];
                this.columnEtiqueta = base.Columns["Etiqueta"];
                this.columnctd_a_fichar = base.Columns["ctd_a_fichar"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            private void InitClass() {
                this.columnBONO = new global::System.Data.DataColumn("BONO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnBONO);
                this.columnEtiqueta = new global::System.Data.DataColumn("Etiqueta", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnEtiqueta);
                this.columnctd_a_fichar = new global::System.Data.DataColumn("ctd_a_fichar", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnctd_a_fichar);
                this.columnBONO.AllowDBNull = false;
                this.columnEtiqueta.AutoIncrement = true;
                this.columnEtiqueta.AllowDBNull = false;
                this.columnEtiqueta.ReadOnly = true;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TC_V_BONO_ETIQUETARow NewTC_V_BONO_ETIQUETARow() {
                return ((TC_V_BONO_ETIQUETARow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new TC_V_BONO_ETIQUETARow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override global::System.Type GetRowType() {
                return typeof(TC_V_BONO_ETIQUETARow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.TC_V_BONO_ETIQUETARowChanged != null)) {
                    this.TC_V_BONO_ETIQUETARowChanged(this, new TC_V_BONO_ETIQUETARowChangeEvent(((TC_V_BONO_ETIQUETARow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.TC_V_BONO_ETIQUETARowChanging != null)) {
                    this.TC_V_BONO_ETIQUETARowChanging(this, new TC_V_BONO_ETIQUETARowChangeEvent(((TC_V_BONO_ETIQUETARow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.TC_V_BONO_ETIQUETARowDeleted != null)) {
                    this.TC_V_BONO_ETIQUETARowDeleted(this, new TC_V_BONO_ETIQUETARowChangeEvent(((TC_V_BONO_ETIQUETARow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.TC_V_BONO_ETIQUETARowDeleting != null)) {
                    this.TC_V_BONO_ETIQUETARowDeleting(this, new TC_V_BONO_ETIQUETARowChangeEvent(((TC_V_BONO_ETIQUETARow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void RemoveTC_V_BONO_ETIQUETARow(TC_V_BONO_ETIQUETARow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                BonoEtiquetas ds = new BonoEtiquetas();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "TC_V_BONO_ETIQUETADataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        public partial class TC_V_BONO_ETIQUETARow : global::System.Data.DataRow {
            
            private TC_V_BONO_ETIQUETADataTable tableTC_V_BONO_ETIQUETA;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            internal TC_V_BONO_ETIQUETARow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableTC_V_BONO_ETIQUETA = ((TC_V_BONO_ETIQUETADataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int BONO {
                get {
                    return ((int)(this[this.tableTC_V_BONO_ETIQUETA.BONOColumn]));
                }
                set {
                    this[this.tableTC_V_BONO_ETIQUETA.BONOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public int Etiqueta {
                get {
                    return ((int)(this[this.tableTC_V_BONO_ETIQUETA.EtiquetaColumn]));
                }
                set {
                    this[this.tableTC_V_BONO_ETIQUETA.EtiquetaColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public double ctd_a_fichar {
                get {
                    try {
                        return ((double)(this[this.tableTC_V_BONO_ETIQUETA.ctd_a_ficharColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("El valor de la columna \'ctd_a_fichar\' de la tabla \'TC_V_BONO_ETIQUETA\' es DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableTC_V_BONO_ETIQUETA.ctd_a_ficharColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public bool Isctd_a_ficharNull() {
                return this.IsNull(this.tableTC_V_BONO_ETIQUETA.ctd_a_ficharColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public void Setctd_a_ficharNull() {
                this[this.tableTC_V_BONO_ETIQUETA.ctd_a_ficharColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public class TC_V_BONO_ETIQUETARowChangeEvent : global::System.EventArgs {
            
            private TC_V_BONO_ETIQUETARow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TC_V_BONO_ETIQUETARowChangeEvent(TC_V_BONO_ETIQUETARow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public TC_V_BONO_ETIQUETARow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace ProyectosOnLine.BonoEtiquetasTableAdapters {
    
    
    /// <summary>
    ///Represents the connection and commands used to retrieve and save data.
    ///</summary>
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.ComponentModel.DataObjectAttribute(true)]
    [global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class TC_V_BONO_ETIQUETATableAdapter : global::System.ComponentModel.Component {
        
        private global::System.Data.SqlClient.SqlDataAdapter _adapter;
        
        private global::System.Data.SqlClient.SqlConnection _connection;
        
        private global::System.Data.SqlClient.SqlCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public TC_V_BONO_ETIQUETATableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private global::System.Data.SqlClient.SqlDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal global::System.Data.SqlClient.SqlConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((global::System.Data.SqlClient.SqlCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected global::System.Data.SqlClient.SqlCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitAdapter() {
            this._adapter = new global::System.Data.SqlClient.SqlDataAdapter();
            global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "TC_V_BONO_ETIQUETA";
            tableMapping.ColumnMappings.Add("BONO", "BONO");
            tableMapping.ColumnMappings.Add("Etiqueta", "Etiqueta");
            tableMapping.ColumnMappings.Add("ctd_a_fichar", "ctd_a_fichar");
            this._adapter.TableMappings.Add(tableMapping);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitConnection() {
            this._connection = new global::System.Data.SqlClient.SqlConnection();
            this._connection.ConnectionString = global::ProyectosOnLine.Properties.Settings.Default.ggConnectionString;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitCommandCollection() {
            this._commandCollection = new global::System.Data.SqlClient.SqlCommand[3];
            this._commandCollection[0] = new global::System.Data.SqlClient.SqlCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = "SELECT        BONO, Etiqueta, Cantidad - ISNULL\r\n                             ((S" +
                "ELECT        SUM(Piezas) AS Piezas\r\n                                 FROM       " +
                "     (SELECT        ISNULL\r\n                                                    " +
                "                                     ((SELECT        marcaCodigo\r\n              " +
                "                                                                               F" +
                "ROM            CS_CPP_0713.dbo.MP_CARGADEPIEZAS\r\n                               " +
                "                                                              WHERE        (id =" +
                " TC_IMPORT_BONOS.id_mp_cargadepiezas)),\r\n                                       " +
                "                                                  (SELECT        TOP (1) MP_CARG" +
                "ADEPIEZAS_1.marcaCodigo\r\n                                                       " +
                "                                    FROM            CS_CPP_0713.dbo.MP_TRABAJOCO" +
                "NBONO INNER JOIN\r\n                                                              " +
                "                                                       CS_CPP_0713.dbo.MP_CARGAD" +
                "EPIEZAS AS MP_CARGADEPIEZAS_1 ON CS_CPP_0713.dbo.MP_TRABAJOCONBONO.id = MP_CARGA" +
                "DEPIEZAS_1.mjTrabajoConBonoId\r\n                                                 " +
                "                                          WHERE        (CS_CPP_0713.dbo.MP_TRABA" +
                "JOCONBONO.id = TC_IMPORT_BONOS.MjTrabajoConBonoId) AND (MP_CARGADEPIEZAS_1.marca" +
                "Cantidad = TC_IMPORT_BONOS.PBUENAS_float))) \r\n                                  " +
                "                                                   AS Etiqueta, TC_IMPORT_BONOS." +
                "PBUENAS_float AS Piezas\r\n                                                       " +
                "    FROM            TC_IMPORT_BONOS INNER JOIN\r\n                                " +
                "                                                     T_OPERAC ON TC_IMPORT_BONOS" +
                ".CODEMP = T_OPERAC.CodEMP AND TC_IMPORT_BONOS.MAQUINA = T_OPERAC.PUESTO\r\n       " +
                "                                                    WHERE        (TC_IMPORT_BONO" +
                "S.CODEMP = TC_V_BONO_ETIQUETA.CODEMP) AND (TC_IMPORT_BONOS.MAQUINA <> \'800\') AND" +
                " (TC_IMPORT_BONOS.ORDFAB_int = TC_V_BONO_ETIQUETA.ORDFAB) AND \r\n                " +
                "                                                                     (T_OPERAC.O" +
                "PERAC = TC_V_BONO_ETIQUETA.OPERAC) AND (TC_IMPORT_BONOS.BONO = TC_V_BONO_ETIQUET" +
                "A.BONO)) AS t_aux\r\n                                 WHERE        (Etiqueta = TC_" +
                "V_BONO_ETIQUETA.Etiqueta)\r\n                                 GROUP BY Etiqueta), " +
                "0) AS ctd_a_fichar\r\nFROM            TC_V_BONO_ETIQUETA\r\nWHERE        (CODEMP = @" +
                "empresa) AND (TIPOREG = \'F\') AND (ORDFAB = @of) AND (OPERAC = @operacion)\r\nORDER" +
                " BY BONO, Etiqueta";
            this._commandCollection[0].CommandType = global::System.Data.CommandType.Text;
            this._commandCollection[0].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@empresa", global::System.Data.SqlDbType.VarChar, 2, global::System.Data.ParameterDirection.Input, 0, 0, "CODEMP", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[0].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@of", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.Input, 0, 0, "ORDFAB", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[0].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@operacion", global::System.Data.SqlDbType.VarChar, 6, global::System.Data.ParameterDirection.Input, 0, 0, "OPERAC", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[1] = new global::System.Data.SqlClient.SqlCommand();
            this._commandCollection[1].Connection = this.Connection;
            this._commandCollection[1].CommandText = "SELECT        BONO, Etiqueta, Cantidad - ISNULL\r\n                             ((S" +
                "ELECT        SUM(Piezas) AS Piezas\r\n                                 FROM       " +
                "     (SELECT        ISNULL\r\n                                                    " +
                "                                     ((SELECT        marcaCodigo\r\n              " +
                "                                                                               F" +
                "ROM            CS_CPP_0713.dbo.MP_CARGADEPIEZAS\r\n                               " +
                "                                                              WHERE        (id =" +
                " TC_IMPORT_BONOS.id_mp_cargadepiezas)),\r\n                                       " +
                "                                                  (SELECT        TOP (1) MP_CARG" +
                "ADEPIEZAS_1.marcaCodigo\r\n                                                       " +
                "                                    FROM            CS_CPP_0713.dbo.MP_TRABAJOCO" +
                "NBONO INNER JOIN\r\n                                                              " +
                "                                                       CS_CPP_0713.dbo.MP_CARGAD" +
                "EPIEZAS AS MP_CARGADEPIEZAS_1 ON CS_CPP_0713.dbo.MP_TRABAJOCONBONO.id = MP_CARGA" +
                "DEPIEZAS_1.mjTrabajoConBonoId\r\n                                                 " +
                "                                          WHERE        (CS_CPP_0713.dbo.MP_TRABA" +
                "JOCONBONO.id = TC_IMPORT_BONOS.MjTrabajoConBonoId) AND (MP_CARGADEPIEZAS_1.marca" +
                "Cantidad = TC_IMPORT_BONOS.PBUENAS_float))) \r\n                                  " +
                "                                                   AS Etiqueta, TC_IMPORT_BONOS." +
                "PBUENAS_float AS Piezas\r\n                                                       " +
                "    FROM            TC_IMPORT_BONOS INNER JOIN\r\n                                " +
                "                                                     T_OPERAC ON TC_IMPORT_BONOS" +
                ".CODEMP = T_OPERAC.CodEMP AND TC_IMPORT_BONOS.MAQUINA = T_OPERAC.PUESTO\r\n       " +
                "                                                    WHERE        (TC_IMPORT_BONO" +
                "S.CODEMP = TC_V_BONO_ETIQUETA.CODEMP) AND (TC_IMPORT_BONOS.MAQUINA <> \'800\') AND" +
                " (TC_IMPORT_BONOS.ORDFAB_int = TC_V_BONO_ETIQUETA.ORDFAB) AND \r\n                " +
                "                                                                     (T_OPERAC.O" +
                "PERAC = TC_V_BONO_ETIQUETA.OPERAC) AND (TC_IMPORT_BONOS.BONO = TC_V_BONO_ETIQUET" +
                "A.BONO)) AS t_aux\r\n                                 WHERE        (Etiqueta = TC_" +
                "V_BONO_ETIQUETA.Etiqueta)\r\n                                 GROUP BY Etiqueta), " +
                "0) AS ctd_a_fichar\r\nFROM            TC_V_BONO_ETIQUETA\r\nWHERE        (CODEMP = @" +
                "empresa) AND (TIPOREG = \'F\') AND (BONO = @bono) AND (OPERAC = @operacion)\r\nORDER" +
                " BY ORDFAB, Etiqueta";
            this._commandCollection[1].CommandType = global::System.Data.CommandType.Text;
            this._commandCollection[1].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@empresa", global::System.Data.SqlDbType.VarChar, 2, global::System.Data.ParameterDirection.Input, 0, 0, "CODEMP", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[1].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@bono", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.Input, 0, 0, "BONO", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[1].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@operacion", global::System.Data.SqlDbType.VarChar, 6, global::System.Data.ParameterDirection.Input, 0, 0, "OPERAC", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[2] = new global::System.Data.SqlClient.SqlCommand();
            this._commandCollection[2].Connection = this.Connection;
            this._commandCollection[2].CommandText = "SELECT        BONO, Etiqueta, Cantidad - ISNULL\r\n                             ((S" +
                "ELECT        SUM(Piezas) AS Piezas\r\n                                 FROM       " +
                "     (SELECT        ISNULL\r\n                                                    " +
                "                                     ((SELECT        marcaCodigo\r\n              " +
                "                                                                               F" +
                "ROM            CS_CPP_0713.dbo.MP_CARGADEPIEZAS\r\n                               " +
                "                                                              WHERE        (id =" +
                " TC_IMPORT_BONOS.id_mp_cargadepiezas)),\r\n                                       " +
                "                                                  (SELECT        TOP (1) MP_CARG" +
                "ADEPIEZAS_1.marcaCodigo\r\n                                                       " +
                "                                    FROM            CS_CPP_0713.dbo.MP_TRABAJOCO" +
                "NBONO INNER JOIN\r\n                                                              " +
                "                                                       CS_CPP_0713.dbo.MP_CARGAD" +
                "EPIEZAS AS MP_CARGADEPIEZAS_1 ON CS_CPP_0713.dbo.MP_TRABAJOCONBONO.id = MP_CARGA" +
                "DEPIEZAS_1.mjTrabajoConBonoId\r\n                                                 " +
                "                                          WHERE        (CS_CPP_0713.dbo.MP_TRABA" +
                "JOCONBONO.id = TC_IMPORT_BONOS.MjTrabajoConBonoId) AND (MP_CARGADEPIEZAS_1.marca" +
                "Cantidad = TC_IMPORT_BONOS.PBUENAS_float))) \r\n                                  " +
                "                                                   AS Etiqueta, TC_IMPORT_BONOS." +
                "PBUENAS_float AS Piezas\r\n                                                       " +
                "    FROM            TC_IMPORT_BONOS INNER JOIN\r\n                                " +
                "                                                     T_OPERAC ON TC_IMPORT_BONOS" +
                ".CODEMP = T_OPERAC.CodEMP AND TC_IMPORT_BONOS.MAQUINA = T_OPERAC.PUESTO\r\n       " +
                "                                                    WHERE        (TC_IMPORT_BONO" +
                "S.CODEMP = TC_V_BONO_ETIQUETA.CODEMP) AND (TC_IMPORT_BONOS.MAQUINA <> \'800\') AND" +
                " (TC_IMPORT_BONOS.ORDFAB_int = TC_V_BONO_ETIQUETA.ORDFAB) AND \r\n                " +
                "                                                                     (T_OPERAC.O" +
                "PERAC = TC_V_BONO_ETIQUETA.OPERAC) AND (TC_IMPORT_BONOS.BONO = TC_V_BONO_ETIQUET" +
                "A.BONO)) AS t_aux\r\n                                 WHERE        (Etiqueta = TC_" +
                "V_BONO_ETIQUETA.Etiqueta)\r\n                                 GROUP BY Etiqueta), " +
                "0) AS ctd_a_fichar\r\nFROM            TC_V_BONO_ETIQUETA\r\nWHERE        (CODEMP = @" +
                "empresa) AND (TIPOREG = \'F\') AND (ORDFAB in (@of)) AND (OPERAC = @operacion)\r\nOR" +
                "DER BY BONO, Etiqueta";
            this._commandCollection[2].CommandType = global::System.Data.CommandType.Text;
            this._commandCollection[2].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@empresa", global::System.Data.SqlDbType.VarChar, 2, global::System.Data.ParameterDirection.Input, 0, 0, "CODEMP", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[2].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@of", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[2].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@operacion", global::System.Data.SqlDbType.VarChar, 6, global::System.Data.ParameterDirection.Input, 0, 0, "OPERAC", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(BonoEtiquetas.TC_V_BONO_ETIQUETADataTable dataTable, string empresa, int of, string operacion) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((empresa == null)) {
                throw new global::System.ArgumentNullException("empresa");
            }
            else {
                this.Adapter.SelectCommand.Parameters[0].Value = ((string)(empresa));
            }
            this.Adapter.SelectCommand.Parameters[1].Value = ((int)(of));
            if ((operacion == null)) {
                throw new global::System.ArgumentNullException("operacion");
            }
            else {
                this.Adapter.SelectCommand.Parameters[2].Value = ((string)(operacion));
            }
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual BonoEtiquetas.TC_V_BONO_ETIQUETADataTable GetData(string empresa, int of, string operacion) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((empresa == null)) {
                throw new global::System.ArgumentNullException("empresa");
            }
            else {
                this.Adapter.SelectCommand.Parameters[0].Value = ((string)(empresa));
            }
            this.Adapter.SelectCommand.Parameters[1].Value = ((int)(of));
            if ((operacion == null)) {
                throw new global::System.ArgumentNullException("operacion");
            }
            else {
                this.Adapter.SelectCommand.Parameters[2].Value = ((string)(operacion));
            }
            BonoEtiquetas.TC_V_BONO_ETIQUETADataTable dataTable = new BonoEtiquetas.TC_V_BONO_ETIQUETADataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, false)]
        public virtual int FillBono(BonoEtiquetas.TC_V_BONO_ETIQUETADataTable dataTable, string empresa, int bono, string operacion) {
            this.Adapter.SelectCommand = this.CommandCollection[1];
            if ((empresa == null)) {
                throw new global::System.ArgumentNullException("empresa");
            }
            else {
                this.Adapter.SelectCommand.Parameters[0].Value = ((string)(empresa));
            }
            this.Adapter.SelectCommand.Parameters[1].Value = ((int)(bono));
            if ((operacion == null)) {
                throw new global::System.ArgumentNullException("operacion");
            }
            else {
                this.Adapter.SelectCommand.Parameters[2].Value = ((string)(operacion));
            }
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, false)]
        public virtual BonoEtiquetas.TC_V_BONO_ETIQUETADataTable GetDataBono(string empresa, int bono, string operacion) {
            this.Adapter.SelectCommand = this.CommandCollection[1];
            if ((empresa == null)) {
                throw new global::System.ArgumentNullException("empresa");
            }
            else {
                this.Adapter.SelectCommand.Parameters[0].Value = ((string)(empresa));
            }
            this.Adapter.SelectCommand.Parameters[1].Value = ((int)(bono));
            if ((operacion == null)) {
                throw new global::System.ArgumentNullException("operacion");
            }
            else {
                this.Adapter.SelectCommand.Parameters[2].Value = ((string)(operacion));
            }
            BonoEtiquetas.TC_V_BONO_ETIQUETADataTable dataTable = new BonoEtiquetas.TC_V_BONO_ETIQUETADataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, false)]
        public virtual int FillTodas(BonoEtiquetas.TC_V_BONO_ETIQUETADataTable dataTable, string empresa, int of, string operacion) {
            this.Adapter.SelectCommand = this.CommandCollection[2];
            if ((empresa == null)) {
                throw new global::System.ArgumentNullException("empresa");
            }
            else {
                this.Adapter.SelectCommand.Parameters[0].Value = ((string)(empresa));
            }
            this.Adapter.SelectCommand.Parameters[1].Value = ((int)(of));
            if ((operacion == null)) {
                throw new global::System.ArgumentNullException("operacion");
            }
            else {
                this.Adapter.SelectCommand.Parameters[2].Value = ((string)(operacion));
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, false)]
        public virtual BonoEtiquetas.TC_V_BONO_ETIQUETADataTable GetDataBy(string empresa, int of, string operacion) {
            this.Adapter.SelectCommand = this.CommandCollection[2];
            if ((empresa == null)) {
                throw new global::System.ArgumentNullException("empresa");
            }
            else {
                this.Adapter.SelectCommand.Parameters[0].Value = ((string)(empresa));
            }
            this.Adapter.SelectCommand.Parameters[1].Value = ((int)(of));
            if ((operacion == null)) {
                throw new global::System.ArgumentNullException("operacion");
            }
            else {
                this.Adapter.SelectCommand.Parameters[2].Value = ((string)(operacion));
            }
            BonoEtiquetas.TC_V_BONO_ETIQUETADataTable dataTable = new BonoEtiquetas.TC_V_BONO_ETIQUETADataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
    }
}

#pragma warning restore 1591