//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34209.
// 
#pragma warning disable 1591

namespace ProyectosOnLine.WebService_Planos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.imedexsa.es/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerFile2OperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarTemporalesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::ProyectosOnLine.Properties.Settings.Default.proyectos_online_WebService_Planos_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerFileCompletedEventHandler ObtenerFileCompleted;
        
        /// <remarks/>
        public event ObtenerFile2CompletedEventHandler ObtenerFile2Completed;
        
        /// <remarks/>
        public event EliminarTemporalesCompletedEventHandler EliminarTemporalesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imedexsa.es/ObtenerFile", RequestNamespace="http://www.imedexsa.es/", ResponseNamespace="http://www.imedexsa.es/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerFile(string marca, string codemp, string user) {
            object[] results = this.Invoke("ObtenerFile", new object[] {
                        marca,
                        codemp,
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerFileAsync(string marca, string codemp, string user) {
            this.ObtenerFileAsync(marca, codemp, user, null);
        }
        
        /// <remarks/>
        public void ObtenerFileAsync(string marca, string codemp, string user, object userState) {
            if ((this.ObtenerFileOperationCompleted == null)) {
                this.ObtenerFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerFileOperationCompleted);
            }
            this.InvokeAsync("ObtenerFile", new object[] {
                        marca,
                        codemp,
                        user}, this.ObtenerFileOperationCompleted, userState);
        }
        
        private void OnObtenerFileOperationCompleted(object arg) {
            if ((this.ObtenerFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerFileCompleted(this, new ObtenerFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imedexsa.es/ObtenerFile2", RequestNamespace="http://www.imedexsa.es/", ResponseNamespace="http://www.imedexsa.es/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerFile2(string marca, string codemp, string user) {
            object[] results = this.Invoke("ObtenerFile2", new object[] {
                        marca,
                        codemp,
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerFile2Async(string marca, string codemp, string user) {
            this.ObtenerFile2Async(marca, codemp, user, null);
        }
        
        /// <remarks/>
        public void ObtenerFile2Async(string marca, string codemp, string user, object userState) {
            if ((this.ObtenerFile2OperationCompleted == null)) {
                this.ObtenerFile2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerFile2OperationCompleted);
            }
            this.InvokeAsync("ObtenerFile2", new object[] {
                        marca,
                        codemp,
                        user}, this.ObtenerFile2OperationCompleted, userState);
        }
        
        private void OnObtenerFile2OperationCompleted(object arg) {
            if ((this.ObtenerFile2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerFile2Completed(this, new ObtenerFile2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.imedexsa.es/EliminarTemporales", RequestNamespace="http://www.imedexsa.es/", ResponseNamespace="http://www.imedexsa.es/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EliminarTemporales(string user) {
            object[] results = this.Invoke("EliminarTemporales", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarTemporalesAsync(string user) {
            this.EliminarTemporalesAsync(user, null);
        }
        
        /// <remarks/>
        public void EliminarTemporalesAsync(string user, object userState) {
            if ((this.EliminarTemporalesOperationCompleted == null)) {
                this.EliminarTemporalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarTemporalesOperationCompleted);
            }
            this.InvokeAsync("EliminarTemporales", new object[] {
                        user}, this.EliminarTemporalesOperationCompleted, userState);
        }
        
        private void OnEliminarTemporalesOperationCompleted(object arg) {
            if ((this.EliminarTemporalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarTemporalesCompleted(this, new EliminarTemporalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ObtenerFileCompletedEventHandler(object sender, ObtenerFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void ObtenerFile2CompletedEventHandler(object sender, ObtenerFile2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerFile2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerFile2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void EliminarTemporalesCompletedEventHandler(object sender, EliminarTemporalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarTemporalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarTemporalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591